import "reflect-metadata";
import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";
import { App } from "antd";

export const metadata: Metadata = {
  title: "四川文产2025军训相册",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AntdRegistry>
          <App>
            {children}
          </App>
        </AntdRegistry>
      </body>
    </html>
  );
}
